#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '=== Linting, Formatting and Testing before committing ==='


# Check tsconfig standards
npx tsc || (
    echo '❌❌❌ Failed Type check. ❌❌❌'
    false;
)

npm run lint ||  (
    echo '❌❌❌ Failed Linting checks. ❌❌❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅ Linting and Styling passed (50% is done)... ✅✅✅'

echo '=== Testing individual components before committing ==='

npm test

echo '✅✅✅ Testing has passed (100% is done)... This change will now be committed ✅✅✅'
